//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WheatherInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    [System.SerializableAttribute()]
    public partial class WheatherInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string humadityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pressureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string speedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string temperatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string humadity {
            get {
                return this.humadityField;
            }
            set {
                if ((object.ReferenceEquals(this.humadityField, value) != true)) {
                    this.humadityField = value;
                    this.RaisePropertyChanged("humadity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.lastUpdateField, value) != true)) {
                    this.lastUpdateField = value;
                    this.RaisePropertyChanged("lastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pressure {
            get {
                return this.pressureField;
            }
            set {
                if ((object.ReferenceEquals(this.pressureField, value) != true)) {
                    this.pressureField = value;
                    this.RaisePropertyChanged("pressure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string speed {
            get {
                return this.speedField;
            }
            set {
                if ((object.ReferenceEquals(this.speedField, value) != true)) {
                    this.speedField = value;
                    this.RaisePropertyChanged("speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string temperature {
            get {
                return this.temperatureField;
            }
            set {
                if ((object.ReferenceEquals(this.temperatureField, value) != true)) {
                    this.temperatureField = value;
                    this.RaisePropertyChanged("temperature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mycompany.com/whether/2010/05/24", ConfigurationName="ServiceReference1.WhetherService")]
    public interface WhetherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mycompany.com/whether/2010/05/24/WhetherService/GetWhetherInfo", ReplyAction="http://www.mycompany.com/whether/2010/05/24/WhetherService/GetWhetherInfoResponse" +
            "")]
        WcfServiceLibrary1.ServiceReference1.WheatherInfo GetWhetherInfo(string city);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.mycompany.com/whether/2010/05/24/WhetherService/GetWhetherInfo", ReplyAction="http://www.mycompany.com/whether/2010/05/24/WhetherService/GetWhetherInfoResponse" +
            "")]
        System.IAsyncResult BeginGetWhetherInfo(string city, System.AsyncCallback callback, object asyncState);
        
        WcfServiceLibrary1.ServiceReference1.WheatherInfo EndGetWhetherInfo(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WhetherServiceChannel : WcfServiceLibrary1.ServiceReference1.WhetherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWhetherInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWhetherInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WcfServiceLibrary1.ServiceReference1.WheatherInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WcfServiceLibrary1.ServiceReference1.WheatherInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WhetherServiceClient : System.ServiceModel.ClientBase<WcfServiceLibrary1.ServiceReference1.WhetherService>, WcfServiceLibrary1.ServiceReference1.WhetherService {
        
        private BeginOperationDelegate onBeginGetWhetherInfoDelegate;
        
        private EndOperationDelegate onEndGetWhetherInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetWhetherInfoCompletedDelegate;
        
        public WhetherServiceClient() {
        }
        
        public WhetherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WhetherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WhetherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WhetherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetWhetherInfoCompletedEventArgs> GetWhetherInfoCompleted;
        
        public WcfServiceLibrary1.ServiceReference1.WheatherInfo GetWhetherInfo(string city) {
            return base.Channel.GetWhetherInfo(city);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetWhetherInfo(string city, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWhetherInfo(city, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WcfServiceLibrary1.ServiceReference1.WheatherInfo EndGetWhetherInfo(System.IAsyncResult result) {
            return base.Channel.EndGetWhetherInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetWhetherInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string city = ((string)(inValues[0]));
            return this.BeginGetWhetherInfo(city, callback, asyncState);
        }
        
        private object[] OnEndGetWhetherInfo(System.IAsyncResult result) {
            WcfServiceLibrary1.ServiceReference1.WheatherInfo retVal = this.EndGetWhetherInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWhetherInfoCompleted(object state) {
            if ((this.GetWhetherInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWhetherInfoCompleted(this, new GetWhetherInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWhetherInfoAsync(string city) {
            this.GetWhetherInfoAsync(city, null);
        }
        
        public void GetWhetherInfoAsync(string city, object userState) {
            if ((this.onBeginGetWhetherInfoDelegate == null)) {
                this.onBeginGetWhetherInfoDelegate = new BeginOperationDelegate(this.OnBeginGetWhetherInfo);
            }
            if ((this.onEndGetWhetherInfoDelegate == null)) {
                this.onEndGetWhetherInfoDelegate = new EndOperationDelegate(this.OnEndGetWhetherInfo);
            }
            if ((this.onGetWhetherInfoCompletedDelegate == null)) {
                this.onGetWhetherInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWhetherInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetWhetherInfoDelegate, new object[] {
                        city}, this.onEndGetWhetherInfoDelegate, this.onGetWhetherInfoCompletedDelegate, userState);
        }
    }
}
