//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WheatherInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class WheatherInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string humadityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pressureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string speedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string temperatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string humadity {
            get {
                return this.humadityField;
            }
            set {
                if ((object.ReferenceEquals(this.humadityField, value) != true)) {
                    this.humadityField = value;
                    this.RaisePropertyChanged("humadity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.lastUpdateField, value) != true)) {
                    this.lastUpdateField = value;
                    this.RaisePropertyChanged("lastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pressure {
            get {
                return this.pressureField;
            }
            set {
                if ((object.ReferenceEquals(this.pressureField, value) != true)) {
                    this.pressureField = value;
                    this.RaisePropertyChanged("pressure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string speed {
            get {
                return this.speedField;
            }
            set {
                if ((object.ReferenceEquals(this.speedField, value) != true)) {
                    this.speedField = value;
                    this.RaisePropertyChanged("speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string temperature {
            get {
                return this.temperatureField;
            }
            set {
                if ((object.ReferenceEquals(this.temperatureField, value) != true)) {
                    this.temperatureField = value;
                    this.RaisePropertyChanged("temperature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mycompany.com/weather", ConfigurationName="ServiceReference1.WeatherService")]
    public interface WeatherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mycompany.com/weather/WeatherService/GetWhetherInfo", ReplyAction="http://www.mycompany.com/weather/WeatherService/GetWhetherInfoResponse")]
        WcfServiceClient.ServiceReference1.WheatherInfo GetWhetherInfo(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mycompany.com/weather/WeatherService/GetWhetherInfo", ReplyAction="http://www.mycompany.com/weather/WeatherService/GetWhetherInfoResponse")]
        System.Threading.Tasks.Task<WcfServiceClient.ServiceReference1.WheatherInfo> GetWhetherInfoAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mycompany.com/weather/WeatherService/GetWhetherInfoSerialized", ReplyAction="http://www.mycompany.com/weather/WeatherService/GetWhetherInfoSerializedResponse")]
        string GetWhetherInfoSerialized(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mycompany.com/weather/WeatherService/GetWhetherInfoSerialized", ReplyAction="http://www.mycompany.com/weather/WeatherService/GetWhetherInfoSerializedResponse")]
        System.Threading.Tasks.Task<string> GetWhetherInfoSerializedAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mycompany.com/weather/WeatherService/SendEmailAsync", ReplyAction="http://www.mycompany.com/weather/WeatherService/SendEmailAsyncResponse")]
        void SendEmailAsync(string city, string receiversAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mycompany.com/weather/WeatherService/SendEmailAsync", ReplyAction="http://www.mycompany.com/weather/WeatherService/SendEmailAsyncResponse")]
        System.Threading.Tasks.Task SendEmailAsyncAsync(string city, string receiversAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherServiceChannel : WcfServiceClient.ServiceReference1.WeatherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherServiceClient : System.ServiceModel.ClientBase<WcfServiceClient.ServiceReference1.WeatherService>, WcfServiceClient.ServiceReference1.WeatherService {
        
        public WeatherServiceClient() {
        }
        
        public WeatherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfServiceClient.ServiceReference1.WheatherInfo GetWhetherInfo(string city) {
            return base.Channel.GetWhetherInfo(city);
        }
        
        public System.Threading.Tasks.Task<WcfServiceClient.ServiceReference1.WheatherInfo> GetWhetherInfoAsync(string city) {
            return base.Channel.GetWhetherInfoAsync(city);
        }
        
        public string GetWhetherInfoSerialized(string city) {
            return base.Channel.GetWhetherInfoSerialized(city);
        }
        
        public System.Threading.Tasks.Task<string> GetWhetherInfoSerializedAsync(string city) {
            return base.Channel.GetWhetherInfoSerializedAsync(city);
        }
        
        public void SendEmailAsync(string city, string receiversAddress) {
            base.Channel.SendEmailAsync(city, receiversAddress);
        }
        
        public System.Threading.Tasks.Task SendEmailAsyncAsync(string city, string receiversAddress) {
            return base.Channel.SendEmailAsyncAsync(city, receiversAddress);
        }
    }
}
